### ISSUE TITLE
[brd_project] Tasks are generated in the parent project

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#241]
How to reproduce: generate multiple projects based on deliverables.
Currently the sub-projects are created for each deliverable but all tasks are assigned to the parent project.
Expected: tasks from each deliverable should be assigned to the corresponding sub-project (linked to the deliverable) .

Affects v8 and v10

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico This Issue is related with #192 

Means we replace partially the relation between BR and Project but still there is quite a lot of crossed references and conditions about `br.linked_project` and `brd.linked_project` (both obsolete).

So is not a quick fix. I will need more time to replace and check the conditions.
So exist dead code as will never called need or should not be take in count

**Comment by martintorresvm** [comment]
@elicoidal Could you dispatch to @YogeshMahera-SerpentCS? 

@YogeshMahera-SerpentCS  Let me know if it's clear. 

If `for_br` and `for_deliverable` is selected means:

create one project per BR
create one project per DL
create one task per RL (If a RL is linked to a DL each RL task should be linked to the related DL project)

Noted that actually `for_br` is default `True` and `editable=False` so it makes no sense check the condition always will generate one project per BR.

As soon as possible I will add a list of dead code to remove regards `linked_project`

**Comment by elicoidal** [comment]
@victormartinelicocorp no I cannot as he is not in the group

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico Solved? Could we close this issue?

**Comment by elicoidal** [comment]
Yes it is soved by #245
