### ISSUE TITLE
[IMP] RL linked to Task

### ISSUE THREAD

**Issue by martintorresvm** [OCA/business-requirement#246]
Need to modify RL to have task_id linked.

When generate project will fill the corresponding task created to the original RL.

module to improve business_requirement_deliverable_project.
models:
class BusinessRequirementResource
+ task_id(
'project_task',
readonly=True,
)

wizard:
After this line:
https://github.com/OCA/business-requirement/blob/8.0/business_requirement_deliverable_project/wizard/generate_projects.py#L226
Need to add:
`line.task_id = task.id`

views:
If RL have task_id the visible

search:

Add group_by:
task_id on RL views

UT updated nice to have.

**Comment by martintorresvm** [comment]
@elicoidal @seb-elico  Please have a look.

**Comment by seb-elico** [comment]
@victormartinelicocorp Thanks, I'm on it!

**Comment by elicoidal** [comment]
to be fixed in v8 and v10

**Comment by seb-elico** [comment]
@elicoidal @victormartinelicocorp Actually this link already exists in the task (field `br_resource_id`) so it's enough on a SQL point of view. ~~Only problem is the data is not up-to-date due to historical reasons (this field has been added recently), so we'll have to "manually" migrate the data.~~

EDIT: After double-checking, it seems the historical data is already ok, I'll update the reports accordingly.

This issue can be closed.
