### ISSUE TITLE
[RFC] Add Reviewer and Estimator info

### ISSUE THREAD

**Issue by mmalorni** [OCA/business-requirement#41]
Create ACL for a Reviewer and Estimator and allow to set the reviewer and estimator in the business requirement form by adding a many 2 many field in the model and in the form view (Employees or users in the drop down list) Allow to set more than one Reviewer and Estimator (many to many)

**Comment by elicoidal** [comment]
:+1: 
@mmalorni can we add fields (reviewer in br module, estimator in br_deliverable modules) with corresponding ACL?
@astirpe

**Comment by elicoidal** [comment]
@victormartinelicocorp Is it implemented?

**Comment by martintorresvm** [comment]
> @victormartinelicocorp Is it implemented?

@elicoidal I think this need further analysis.

`Estimator` like field new but I think it's always implicit. Because normally we set a DL with at least one RL and on that RL is the estimation (Hours, Days for time, Currency for money, etc)

Then who approves the BR is responsible of that estimation or not? or means is the Estimator? 
For me seems very fuzzy and could means nobody is sure from which part is `responsible`

Also why is need more than one? If they have different opinion how to deal.

`Reviewer` already we have explicit and is mean to be filled by workflow. (If you click `Confirm` then means it's have been review by you)

**Comment by elicoidal** [comment]
> Reviewer already we have explicit and is mean to be filled by workflow. (If you click Confirm then means it's have been review by you)

those 2 fields are here to assign the job so that people can filter on their name and see what they have to do, not to record the confirmation (which as you pointed out is already done).

I agree that Estimator might be fuzzy because some question might be technical, some functional.

So I would keep the reviewer and remove the estimator

**Comment by martintorresvm** [comment]
@elicoidal One more question.
So imagine you ask me review a BR.
I add myself as a reviewer.
On which states should be possible edit this field?
Draft / Confirm and Approved?
cc @seb-elico

The ACL of course I think should only allow to my own user.
And the event of add a reviewer should be trace on the messages

**Comment by elicoidal** [comment]
@victormartinelicocorp 

> Draft / Confirm and Approved?

OK with that

> The ACL of course I think should only allow to my own user.

I would say that the BR responsible and anybody in BR Manager group could do that only
